package com.knowflick.app.data

import com.knowflick.app.domain.KnowledgeCard
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * 卡片批量导出引擎（移植自 macOS CardExportEngine）：
 * - 单文件 Markdown（目录 card-N 锚点与正文一致、来源三分支、浏览时间口径）
 * - Anki TSV（正面主张 / 背面机理）
 * - JSON 归档（cards.json 同构线格式）
 */
object CardExportEngine {

    /** 单文件 Markdown 导出（O(行) 数组 join，非 O(n²) 拼接） */
    fun exportMarkdownSingleFile(cards: List<KnowledgeCard>, title: String = "KnowFlick 知识卡片"): String {
        val dateFmt = SimpleDateFormat("yyyy-MM-dd HH:mm", java.util.Locale.CHINA)
        val nowStr = dateFmt.format(java.util.Date())

        val lines = ArrayList<String>(cards.size * 16 + 24)
        lines += """
        ---
        title: "$title"
        date: "$nowStr"
        total_cards: ${cards.size}
        tags: [knowflick, study-notes, flashcards]
        generator: KnowFlick Android
        ---

        # 📚 $title

        > 沉淀闪念，连接灵感。本次共导出 **${cards.size}** 张知识卡片。
        > 导出时间：$nowStr

        ---

        ## 📑 目录索引

        """.trimIndent()

        cards.forEachIndexed { idx, card ->
            val clean = card.headline.replace("\n", " ")
            lines += "${idx + 1}. [${card.category} · $clean](#card-${idx + 1})"
        }

        lines += "\n---\n\n## 💡 知识笔记详情\n\n"

        cards.forEachIndexed { idx, card ->
            val categoryName = card.category.ifBlank { "未分类" }
            val seenTimeStr = card.seenAt?.let { dateFmt.format(java.util.Date(it)) } ?: "待刷中"
            val sourceName = when (card.source.raw) {
                "ai" -> "🤖 AI 灵感探索"
                "seed" -> "🌱 精选经典"
                else -> "📥 个人笔记提纯"
            }
            lines += """
            <a id="card-${idx + 1}"></a>
            ### ${idx + 1}. ${card.headline.replace("\n", " ")}

            - **领域分类**：`$categoryName`
            - **收录状态**：`$seenTimeStr`
            - **知识来源**：$sourceName
            - **记忆熟练度**：${masteryLabel(card.masteryLevel)}

            > **核心观点**
            > ${card.summary}

            **深入剖析**
            ${card.details}

            """.trimIndent()
            if (card.links.isNotEmpty()) {
                lines += "\n**延伸阅读**"
                card.links.forEach { link -> lines += "- [${link.title}](${link.url})" }
            }
            lines += "\n---\n\n"
        }
        lines += "*Generated by KnowFlick (闪念智库)*\n"
        return lines.joinToString("\n")
    }

    /** Anki TSV：正面核心主张，背面机理解析 */
    fun exportAnkiTSV(cards: List<KnowledgeCard>): String {
        val lines = ArrayList<String>(cards.size + 1)
        lines += "front\tback\tcategory"
        cards.forEach { card ->
            val front = card.headline.replace("\t", " ").replace("\n", " ")
            val back = card.details.replace("\t", " ")
            lines += "$front\t$back\t${card.category}"
        }
        return lines.joinToString("\n")
    }

    /** JSON 归档（cards.json 同构线格式，含复习进度，跨端迁移） */
    fun exportJSONArchive(cards: List<KnowledgeCard>): String = CardFileIO.encodeList(cards)

    fun sourceLabel(card: KnowledgeCard): String = when (card.source.raw) {
        "ai" -> "🤖 AI 灵感探索"
        "seed" -> "🌱 精选经典"
        else -> "📥 个人笔记提纯"
    }

    fun masteryLabel(level: Int): String = when (level) {
        2 -> "已掌握 (★★)"
        1 -> "学习中 (★☆)"
        else -> "未测验 (☆☆)"
    }
}
